name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  windows:
    runs-on: [windows-latest]
    strategy:
      matrix:
        java: [17]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'liberica'
      - run: choco install nsis
      - run: ant nsis
      - run: Start-Process -Wait ./out/qz-tray-*.exe -ArgumentList "/S"
      - run: "&'C:/Program Files/QZ Tray/qz-tray.exe' --wait --version|Out-Null"
      - uses: actions/upload-artifact@v4
        with:
          path: 'D:\a\qz-tray\qz-tray\out\qz-tray-2.2.4-YoYo-x86_64.exe'
